name: Build and Test Todo library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [llvm, gcc]
        exclude: # Excluding llvm on MacOS until the <source_location> is present.
          - os: macos-latest
            compiler: llvm
        include:
          - os: windows-latest
            compiler: msvc
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Todo
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Todo

    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test_todo

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
